import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Reinado Pokemon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="min-h-screen w-screen flex flex-col justify-center items-center">
          <h1 className="text-2xl text-center pb-8">
            ¿Cual Pokemon es más bello?
          </h1>
          <div className="border rounded p-8 flex justify-between items-center max-w-2xl">
            <div className="w-16 h-16 bg-red-200"></div>
            <div className="p-8">VS</div>
            <div className="w-16 h-16 bg-red-200"></div>
            
          </div>
        </main>
    </>
  );
};

export default Home;
